// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCByWzZB0EUXTsY9LFkHzBra25jOZUwc3w',
    appId: '1:590519900133:web:c588e505983ce5b133c10c',
    messagingSenderId: '590519900133',
    projectId: 'check-in-d72d2',
    authDomain: 'check-in-d72d2.firebaseapp.com',
    storageBucket: 'check-in-d72d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHQDs4ODAFc7S_aOP8OU2WEF8-iME8m4',
    appId: '1:590519900133:android:7754a5de12884eda33c10c',
    messagingSenderId: '590519900133',
    projectId: 'check-in-d72d2',
    storageBucket: 'check-in-d72d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxAhbUCp3JDJiS8RKTy7gXQCT1uzwkzI',
    appId: '1:590519900133:ios:4929f8f05ef1b8f733c10c',
    messagingSenderId: '590519900133',
    projectId: 'check-in-d72d2',
    storageBucket: 'check-in-d72d2.appspot.com',
    iosClientId: '590519900133-p94bpmv52lgmk1l01q6ncorhgbb4begd.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbxAhbUCp3JDJiS8RKTy7gXQCT1uzwkzI',
    appId: '1:590519900133:ios:4929f8f05ef1b8f733c10c',
    messagingSenderId: '590519900133',
    projectId: 'check-in-d72d2',
    storageBucket: 'check-in-d72d2.appspot.com',
    iosClientId: '590519900133-p94bpmv52lgmk1l01q6ncorhgbb4begd.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkIn',
  );
}
